global:
  name: "ARBITER"
  version: "1.4.0"
  user_agent: "Sentinel-NG/1.4"
  timeout: 5
  max_retries: 2
  active_validation: true  # NEW: Toggles key testing

modes:
  stealth:
    threads: 10
    nuclei_rate: 5
    jitter: true
    scan_delay: 1
    ports: "top-100"
    description: "Low-noise scan."
  
  standard:
    threads: 50
    nuclei_rate: 50
    jitter: false
    scan_delay: 0
    ports: "top-1000"
    description: "Balanced scan."

  balanced:
    threads: 50
    nuclei_rate: 50
    jitter: false
    scan_delay: 0
    ports: "top-1000"
    description: "Alias for Standard."

  loud:
    threads: 200
    nuclei_rate: 150
    jitter: false
    scan_delay: 0
    ports: "full"
    description: "Aggressive scan."

tools:
  nuclei:
    path: "nuclei"
  subfinder:
    path: "subfinder"
  httpx:
    path: "httpx"
  naabu:
    path: "naabu"
  s3enum:
    path: "/home/syed/go/bin/s3enum"
    wordlist: "data/wordlists/buckets.txt"
  cloud_enum:
    path: "/home/syed/cloud_enum/cloud_enum.py"
